# DO NOT EDIT!
# This file was automatically generated by "/Users/Reynald/PycharmProjects/python-sc2/generate_id_constants_from_stableid.py"

__all__ = ['unit_typeid', 'ability_id', 'upgrade_id', 'buff_id', 'effect_id']
