# DO NOT EDIT!
# This file was automatically generated by "generate_id_constants_from_stableid.py"

import enum

class EffectId(enum.Enum):
    Null = 0
    PsiStormPersistent = 1
    GuardianShieldPersistent = 2
    TemporalFieldGrowingBubbleCreatePersistent = 3
    TemporalFieldAfterBubbleCreatePersistent = 4
    ThermalLancesForward = 5
    ScannerSweep = 6
    NukePersistent = 7
    LiberatorTargetMorphDelayPersistent = 8
    LiberatorTargetMorphPersistent = 9
    BlindingCloudCP = 10
    RavagerCorrosiveBileCP = 11
    LurkerMP = 12

for item in EffectId:
    assert not item.name in globals()
    globals()[item.name] = item
